package io.github.naimjeg.obeliskdepths.dungeon.lifecycle;

import io.github.naimjeg.obeliskdepths.dungeon.artifact.DungeonRuntimeArtifactCleanupService;
import io.github.naimjeg.obeliskdepths.dungeon.instance.DungeonInstance;
import io.github.naimjeg.obeliskdepths.dungeon.instance.DungeonInstanceService;
import io.github.naimjeg.obeliskdepths.dungeon.instance.DungeonStatus;
import io.github.naimjeg.obeliskdepths.dungeon.session.DungeonSessionCleanup;
import io.github.naimjeg.obeliskdepths.dungeon.site.DungeonSiteUsageStatus;
import io.github.naimjeg.obeliskdepths.dungeon.state.DungeonManagerSavedData;
import net.minecraft.server.level.ServerLevel;

import java.util.ArrayList;
import java.util.List;

/*
 * New model:
 * Cleanup removes runtime metadata only.
 *
 * It must not delete terrain, rooms, corridors, or decoration blocks because
 * those are generated by worldgen/chunk generation.
 */
public final class DungeonCleanupService {
    private static final long CLOSED_INSTANCE_CLEANUP_DELAY_TICKS = 20L * 60L * 5L;

    private DungeonCleanupService() {
    }

    public static int cleanupPortalClosedInstances(ServerLevel dungeonLevel) {
        DungeonManagerSavedData data = DungeonManagerSavedData.get(dungeonLevel);

        List<DungeonInstance> targets = new ArrayList<>();

        for (DungeonInstance instance : data.instances().all()) {
            if (instance.status() == DungeonStatus.PORTAL_CLOSED
                    || instance.status() == DungeonStatus.FAILED
                    || instance.status() == DungeonStatus.EXPIRED) {
                targets.add(instance);
            }
        }

        return removeInstances(dungeonLevel, targets);
    }

    public static int cleanupClosedInstancesReadyForCleanup(ServerLevel dungeonLevel) {
        DungeonManagerSavedData data = DungeonManagerSavedData.get(dungeonLevel);

        List<DungeonInstance> targets =
                data.instances().findClosedReadyForCleanup(
                        dungeonLevel.getGameTime(),
                        CLOSED_INSTANCE_CLEANUP_DELAY_TICKS
                );

        return removeInstances(dungeonLevel, targets);
    }

    private static int removeInstances(
            ServerLevel dungeonLevel,
            List<DungeonInstance> targets
    ) {
        int cleaned = 0;

        for (DungeonInstance instance : targets) {
            DungeonSiteUsageStatus finalStatus =
                    instance.status() == DungeonStatus.CLEARED
                            ? DungeonSiteUsageStatus.COMPLETED
                            : DungeonSiteUsageStatus.ABANDONED;

            DungeonSessionCleanup.cleanupSessionsForInstance(
                    dungeonLevel,
                    instance.id()
            );
            DungeonRuntimeArtifactCleanupService.cleanupInstanceArtifacts(
                    dungeonLevel,
                    instance.id()
            );

            if (DungeonInstanceService.retireRuntimeInstance(
                    dungeonLevel,
                    instance.id(),
                    finalStatus,
                    dungeonLevel.getGameTime()
            )) {
                cleaned++;
            }
        }

        return cleaned;
    }
}
